version: '3'

services:
  flask1:
    build: .
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - app-network

  flask2:
    build: .
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask1
      - flask2
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge